sudo: true
os: linux
language: python

python:
    - "3.5"

env:
- ASSIGNMENT_REPO=https://github.com/tgteacher/BigData-LA1.git PYTHONHASHSEED=0 PYTHONPATH=$PYTHONPATH:$PWD/answers

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - pip install pyspark pytest "dask[complete]"
  # The two lines below ensure that everybody will run the same tests in
  # case they are updated
  - \mv -f tests tests.old
  - git clone $ASSIGNMENT_REPO vanilla
  - \mv -f vanilla/tests .

script:
 - pytest tests

after_success:
  - echo "success"

after_failure:
  - echo "failure"
